apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applicationmonitorings.applicationmonitoring.integreatly.org
spec:
  group: applicationmonitoring.integreatly.org
  names:
    kind: ApplicationMonitoring
    listKind: ApplicationMonitoringList
    plural: applicationmonitorings
    singular: applicationmonitoring
  scope: Namespaced
  version: v1alpha1              