apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ application_monitoring_operator_role }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - prometheusrules
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - applicationmonitoring.integreatly.org
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - integreatly.org
    resources:
      - grafanadashboards
      - grafanas
      - grafanas/finalizers
    verbs:
      - '*'
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    attributeRestrictions: null
    resources:
      - rolebindings
      - roles
    verbs:
      - '*'
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - '*'