apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    k8s-app: prometheus
    monitoring-key: "{{ application_monitoring_label_value }}"
  name: metrics-monitor-services
spec:
  endpoints:
    - interval: 5s
      port: http
  selector:
    matchLabels:
      monitoring: {{ monitoring_label }}
