apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ application_monitoring_operator_deployment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ application_monitoring_operator_deployment }}
  template:
    metadata:
      labels:
        name: {{ application_monitoring_operator_deployment }}
    spec:
      serviceAccountName: {{ application_monitoring_operator_sa }}
      containers:
        - name: application-monitoring-operator
          image: docker.io/aidenkeatingrht/application-monitoring-operator:0.0.5-monitoring-key
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - application-monitoring-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: TEMPLATE_PATH
              value: /usr/local/bin/templates
            - name: MONITORING_KEY
              value: {{ application_monitoring_key }}
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "application-monitoring-operator"