apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
    monitoring-key: "{{ application_monitoring_label_value }}"
  name: metrics-monitor-kafka
spec:
  endpoints:
    - interval: 5s
      port: metrics
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
