apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ monitoring_prometheus_operator_clusterrolebinding }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-application-monitoring-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: "{{ namespace }}"
userNames:
- system:serviceaccount:{{ namespace }}:prometheus-operator
